# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 18:45
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=1048576)),
                ('last_edited', models.DateTimeField(auto_now_add=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=256)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleTagVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('defined_by_article', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=256, validators=[django.core.validators.RegexValidator('^[0-9a-z-]+$', 'Only lowercase letters "a-z", digits "0-9" and hyphens "-" are allowed.')])),
                ('value', models.IntegerField(choices=[(1, 'Upvote'), (-1, 'Downvote')], default=1)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='free_books.Article')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('type', models.IntegerField(choices=[(0, 'Like')], default=1)),
                ('value', models.IntegerField(choices=[(1, 'Upvote'), (-1, 'Downvote')], default=1)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='free_books.Article')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('last_edited', models.DateTimeField(auto_now_add=True, verbose_name='profile last edited')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='articlevote',
            unique_together=set([('article', 'creator', 'type')]),
        ),
        migrations.AlterUniqueTogether(
            name='articletagvote',
            unique_together=set([('article', 'creator', 'defined_by_article', 'name')]),
        ),
    ]
