# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 07:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free_books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='last_edited',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 10, 7, 37, 41, 955624)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
