# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free_books', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reputation',
            field=models.BigIntegerField(default=0),
        ),
    ]
