# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 22:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('free_books', '0005_articlevote'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='votes',
            field=models.ManyToManyField(related_name='voted_articles', through='free_books.ArticleVote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
