# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 11:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('free_books', '0006_auto_20160514_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlevote',
            name='value',
            field=models.IntegerField(choices=[(0, 'Upvote'), (1, 'Downvote')], default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='votes',
            field=models.ManyToManyField(related_name='article_votes', through='free_books.ArticleVote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articlevote',
            name='type',
            field=models.IntegerField(choices=[(0, 'Like')], default=0),
        ),
        migrations.AlterUniqueTogether(
            name='articlevote',
            unique_together=set([('article', 'type', 'user')]),
        ),
    ]
