# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free_books', '0008_auto_20160515_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='pub_date',
            new_name='date_published',
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_edited',
            field=models.DateTimeField(auto_now_add=True, verbose_name='profile last edited'),
        ),
    ]
