# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free_books', '0010_auto_20160519_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='votes',
        ),
        migrations.AlterField(
            model_name='articlevote',
            name='type',
            field=models.IntegerField(choices=[(0, 'Like')], default=1),
        ),
        migrations.AlterField(
            model_name='articlevote',
            name='value',
            field=models.IntegerField(choices=[(1, 'Upvote'), (-1, 'Downvote')], default=1),
        ),
    ]
