# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('free_books', '0011_auto_20160522_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlevote',
            old_name='user',
            new_name='creator',
        ),
        migrations.AlterUniqueTogether(
            name='articlevote',
            unique_together=set([('article', 'creator', 'type')]),
        ),
    ]
