# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('free_books', '0014_auto_20160524_1931'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleTag',
            new_name='ArticleTagVote',
        ),
    ]
