# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('free_books', '0015_auto_20160525_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articletagvote',
            old_name='slug',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='articletagvote',
            unique_together=set([('article', 'creator', 'defined_by_article', 'name')]),
        ),
    ]
